ZSH=$HOME/.oh-my-zsh

if [[ -d "$HOME/.zsh-completions/src" ]]; then
	fpath=($fpath ~/.zsh-completions/src)
fi

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)
if [ `uname` = 'Darwin' ]; then
	plugins=($plugins brew)
fi
source $ZSH/oh-my-zsh.sh

export PATH=$HOME/bin:$PATH

# prompt
eval "$(starship init zsh)"

# alias
alias ls='ls -G'
alias ll='ls -l'
alias u='cd ..'
alias uu='cd ../..'
alias uuu='cd ../../..'
alias tmux="tmux -2 -u"
alias sk="sk --layout=reverse --ansi"
alias skp='sk --layout=reverse --ansi --preview="preview.sh {}"'
alias g='cd $(ghq root)/$(ghq list|sk)'
alias groot='cd $(git rev-parse --show-toplevel)'
alias -g X="|xargs -o"
alias -g "$"="|xargs -o"
alias -g L="|less"

# z
source ~/.z.sh/z.sh;

setopt extended_glob
setopt auto_param_keys # カッコの対応などを自動的に補完
setopt correct # スペルチェック
setopt hist_ignore_all_dups

# zmv
autoload -Uz zmv
alias zmv='noglob zmv'

function chpwd() {
    ls;
}

for rc in `ls ~/.zshrc.d/*`; do
  source $rc
done

source ~/.zshrc.local;

# TODO: 呼び出し削減
autoload -U compinit
compinit
