include_cookbook 'base'

include_cookbook 'z'
include_cookbook 'zsh'
include_cookbook 'ghq'
include_cookbook 'git'
include_cookbook 'vim'
include_cookbook 'tmux'
include_cookbook 'anyenv'
include_cookbook 'direnv'
include_cookbook 'poetry'